### ISSUE TITLE
Retain Copyright notices and properly attribute sources from other projects

### ISSUE THREAD

**Issue by michael-hawker** [ghost1372/DevWinUI#6]
Hi,

I noticed you've included some code in your project from the [Windows Community Toolkit](https://github.com/CommunityToolkit/Windows).

It seems like in some files the header has been preserved, as they should be:

https://github.com/ghost1372/DevWinUI/blob/4694a9195d7163c3d0dcd8214d5e65e7389c7671/dev/DevWinUI.Controls/Controls/Ported/UniformGrid/UniformGrid.cs#L1-L3

But in other places it has not, e.g. (but not limited to):

- https://github.com/ghost1372/DevWinUI/tree/main/dev/DevWinUI.Controls/Controls/ImageEx
- https://github.com/ghost1372/DevWinUI/tree/main/dev/DevWinUI.Controls/Controls/Ported/SwitchPresenter

Based on the MIT license, you need to be properly attributing this code that you've included in your own project and [shouldn't remove the copyright header](https://opensource.org/faq#preserve-copyright-notices:~:text=source%20software%20(FOSS).%E2%80%9D-,Can%20I%20strip%20out%20the%20copyrights%20on%20Open%20Source%20code%20and%20put%20in%20my%20own%3F,-Definitely%20not!%20This).

Ideally, you should also have more central notices that indicate the inclusion and source of this code, e.g. in the readme, license, or a notice/third-party-notice type file, you can see how this is done in some of our projects, for example here: https://github.com/CommunityToolkit/dotnet/blob/main/ThirdPartyNotices.txt (which is included in its NuGet package as well)

I'm curious why you've chosen to reference some of the toolkit project's NuGet packages directly vs. copying the code in others? If there are improvements you're making, it'd be great to improve them in the toolkit itself. In the meantime, it'd be great if you could properly credit the toolkit's source code in your project.

Thanks!

**Comment by ghost1372** [comment]
Hi, yes, unfortunately some headers were forgotten when copying, I will try to respect copyright and add them soon.

I copied some controls into my project (like imageEx) because I needed some of their features, but I have not used them as dedicated controls anywhere, neither in Readme nor in the code samples and the gallery app.

Also, the toolkit packages are released very late (For example, some controls only recently supported AOT in preview versions. But I added AOT support at the same time as version 1.6 was released.) and I have modified some of them according to my needs.
Some of the changes are superficial and not according to the toolkit standards.(That's why I didn't create a PR in the main repository.)
Regarding the settings control, I first ported it from PowerToys and released it in Nuget under the title SettingsUI. At that time, the toolkit had not yet created this control.Then I took the completed version from the toolkit and made some changes to it.

Anyway, I respect your work and try to respect all licensing rights.
I will remove some controls but I need some because I have made changes to them.
Thanks for reminding me of this.
